# Neural Network machine learning model that classifies images.

In [1]:
#import dependencies and print the version

import tensorflow as tf
print("Tensorflow version: ",tf.__version__)

Tensorflow version:  2.12.0


In [3]:
#load and prepare the MNIST dataset
""" The pixel values of the images range from 0 through 255. 
Scale these values to a range of 0 to 1 by dividing the values by 255.0. 
This also converts the sample data from integers to floating-point numbers"""

mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
#Build a tf.keras.Sequential model

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

"""Sequential is useful for stacking layers where each layer has one input tensor and one output tensor. 
Layers are functions with a known mathematical structure that can be reused and have trainable variables. 
Most TensorFlow models are composed of layers. This model uses the Flatten, Dense, and Dropout layers"""

In [5]:
#model returns a vector of logits or log-odds scores, one for each class

predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.08309615, -0.09980469,  0.18545529,  0.08567674, -0.57978845,
         0.25442043,  0.03414473,  0.10578331,  0.07636791,  0.39197958]],
      dtype=float32)

In [6]:
#tf.nn.softmax function converts these logits to probabilities for each class

tf.nn.softmax(predictions).numpy()

array([[0.10024232, 0.08348689, 0.11104658, 0.10050134, 0.05166114,
        0.11897517, 0.09545349, 0.10254253, 0.09957014, 0.13652039]],
      dtype=float32)

In [8]:
#define loss function for training using losses.SparseCategoricalCrossentropy

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

"""The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example.
 This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class."""

In [9]:
#untrained model initial loss

loss_fn(y_train[:1],predictions).numpy()

2.1288404

In [10]:
#before training,configure and compile the model using Keras Model.compile.
#set the optimizer class to adam, set the loss to the loss_fn function you defined earlier and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy

model.compile(optimizer= 'adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
#Train an devaluate the model

model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2981 - accuracy: 0.9135
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1429 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1068 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0879 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0744 - accuracy: 0.9773


In [12]:
#check the model performance

model.evaluate(x_test,y_test, verbose=2)

313/313 - 1s - loss: 0.0756 - accuracy: 0.9762 - 557ms/epoch - 2ms/step


[0.07563043385744095, 0.9761999845504761]

In [13]:
#to return a probability

probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.15838938e-07, 2.54839505e-09, 3.21319681e-06, 1.23296821e-04,
        2.61027415e-11, 1.65444661e-07, 8.40939406e-13, 9.99871850e-01,
        7.25560767e-08, 1.19727304e-06],
       [2.43137208e-07, 5.10046165e-03, 9.94884312e-01, 9.09086884e-06,
        8.74391011e-12, 4.75774232e-06, 4.38247099e-07, 9.03235819e-11,
        5.65560583e-07, 3.69276902e-13],
       [3.26749699e-07, 9.99728382e-01, 1.61423231e-05, 1.39202375e-05,
        6.90631987e-06, 1.02269214e-05, 6.87773863e-05, 7.02909820e-05,
        8.45419781e-05, 4.32693895e-07],
       [9.98486638e-01, 5.52497492e-10, 1.01760328e-04, 8.58002693e-07,
        1.22928368e-05, 8.73788395e-06, 1.25156483e-03, 1.23868012e-04,
        1.78427157e-07, 1.41626715e-05],
       [2.77442791e-06, 2.36022188e-08, 2.19832782e-05, 6.88166253e-08,
        9.99678493e-01, 7.43570467e-07, 5.17849139e-06, 6.04085217e-05,
        2.36308028e-06, 2.27966113e-04]], dtype=float32)>